### ISSUE TITLE
Interpreting alpha

### ISSUE THREAD

**Issue by arunasank** [LightTag/simpledorff#4]
![image (16)](https://user-images.githubusercontent.com/3166852/141811640-85b37c4c-00b3-4b79-b03e-d4c61c8faf61.png)

The above subset of the data gives me an alpha value of 0, and I am stumped becauset he data looks a lot like the one in the documentation. Can you please help me understand what's going on here?

**Comment by talolard** [comment]
Hi,
 In your case there is a single experiment. Kripendor's alpha tries to estimate how much more likely the agreement is than a random guessing. Since there is only one experiment, the calculations estimation of random makes it so that it can't distinguish between your input and random, hence  a value of 0. 
Try doing the same with more than 1 experiment
